### PR TITLE
fix: Typo on "been"

### PR DESCRIPTION
**Pull request by kingthorin**
Change "has ben" to "has been".

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by kingthorin** [comment]
Ping @michaelficarra @bakkot 🙂

**Review by michaelficarra — APPROVED** [review]

**Comment by michaelficarra** [comment]
Unfortunately our CI setup with Travis seems to be broken, and I don't have the time to fix it right now.

**Comment by kingthorin** [comment]
Okay, thanks for following up.

**Comment by kingthorin** [comment]
Is there something I can do to help keep this project alive?

**Comment by michaelficarra** [comment]
@kingthorin The project is alive and is being used in critical production systems in @shapesecurity (and its customers, which include major banks, airlines, hotels, etc). If there is a bug, it will be fixed. New features will be added as needed. But for a typo, it's not worth it right now for me to figure out some issue with the Travis CI integration. Eventually, we will address that issue (probably by ditching Travis for GH Actions) and merge your PR. Thanks for the contribution and sorry for the delay.

**Comment by kingthorin** [comment]
No no, it’s all good. I wasn’t thinking solely of this little agreeably lame PR, but some of the other issues in the tracker etc. I’m glad to hear it is used elsewhere, I was kinda wondering if ZAP was a one off.

Thanks for staying in-touch and please do let me know if there’s something I can do to help.

**Comment by kingthorin** [comment]
I’ll rebase this shortly so that it picks up the new CI changes.

**Comment by kingthorin** [comment]
Hmmm it merged instead of rebasing 😞 Will get it sorted soon.

**Comment by bakkot** [comment]
> Hmmm it merged instead of rebasing 😞 Will get it sorted soon.

Don't worry about it; the squash-and-merge button will create a single commit on the main branch even if there's merge commits on this branch.

Also it'll need another update to pick up https://github.com/shapesecurity/salvation/pull/252 anyway.

**Comment by kingthorin** [comment]
Okay I’ll watch for 252 to be merged, thanks again!

After this is all sorted I’ll tackle some minor issue that SonarLint detects. Then I’m thinking of looking into handling trusted types.

**Pull request merged**
