### PR TITLE
Address deprecation of plugin-types and prefetch-src

### PR DESCRIPTION
**Pull request by kingthorin**
- Policy > Updated with appropriate deprecation notices and handling.
- Test classes > Updated to assert the new behavior and ignore errors where applicable.

Related to: https://github.com/zaproxy/zaproxy/issues/8077 and https://github.com/zaproxy/zap-extensions/pull/4950

### CODE REVIEW

**Comment by kingthorin** [comment]
Ping @bakkot / @disnet 😀

**Comment by kingthorin** [comment]
I don't mean to be a pain, but I'd be happy to tackle more if we could move this along 😀

**Comment by kingthorin** [comment]
Anyone out there?

**Comment by rbri** [comment]
@kingthorin becauese HtmlUnit needs this (and i have) i'm currently thinking about a fork - do you like to support that?

**Comment by kingthorin** [comment]
I'll email you.

**Comment by kingthorin** [comment]
@rbri is the email on your profile/commits one you actually use? 😉

**Pull request closed without merging**
