### PR TITLE
Added base-uri allows checks to policy

### PR DESCRIPTION
**Pull request by kingthorin**
Similar to shapesecurity/salvation#152.

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by kingthorin** [comment]
Ping @shekyan 😀

**Comment by michaelficarra** [comment]
@kingthorin Yes, it is in the process of a [major redesign](https://github.com/shapesecurity/salvation/pull/238).

**Comment by kingthorin** [comment]
Okay, thanks.

**Comment by kingthorin** [comment]
Not to rush or pressure, more because I’m nosey 🙂

1. Is there an ETA, even a rough one on that?
2. Will the public API (for users of the lib) remain the same?

**Comment by kingthorin** [comment]
@michaelficarra the re-write seems stalled. Is there any chance I could convince you to review/merge my two PRs and do a release? (So that we can leverage them downstream.)

**Comment by michaelficarra** [comment]
@kingthorin The work is not stalled. We are targeting a release of the rewrite this week. Sorry for the delay.

**Comment by kingthorin** [comment]
Oh wow, okay that's great. I think I'd ignored the recent pushes and just focused on the comments that were back at early May. Sorry about that, thanks for getting back to me 👍

**Comment by kingthorin** [comment]
Any idea when 3.x will be released via Maven so that we can start looking into adapting to it?

Can you confirm that 3.x addresses the change made in this PR?

**Comment by bakkot** [comment]
3.x was released last week under the salvation2 name. (Java's not so good with breaking changes, so I figured it was worth changing the package name.) It doesn't include this change because the HTML side of this, involving the document's fallback base URL, is somewhat complicated - it's not quite a matter of just looking at the page's URL. But I'll try to address this as well.

**Comment by kingthorin** [comment]
Thanks @bakkot I'll look for it under the [new name](https://mvnrepository.com/artifact/com.shapesecurity/salvation2) and start putting things together.

**Pull request closed without merging**
