### PR TITLE
Issue 248: Do not parse directives which are missing a space before the value

### PR DESCRIPTION
**Pull request by elijms**
Addresses [Issue 248](https://github.com/shapesecurity/salvation/issues/248), wherein directives that have a value that does not contain a leading whitespace character should not be parsed.

### CODE REVIEW

**Comment by kingthorin** [comment]
```bash
ERROR: Committer e.schlenker@f5.com has not signed the CLA

Please submit a PR to the CLA located at [https://github.com/shapesecurity/CL](https://github.com/shapesecurity/CLA)
```

**Comment by bakkot** [comment]
We evidently haven't updated the CLA script since the acquisition, lol. I'll get to that Monday.

**Review by bakkot — APPROVED** [review]

**Comment by kingthorin** [comment]
Should we add such directives to the notices list?

**Comment by bakkot** [comment]
@kingthorin Oh jeeze, good call, I forgot we switched to reporting errors through the error consumer. I'll open a PR.

**Comment by kingthorin** [comment]
No problem.

Also I guess default-src should get a special notice since if it’s malformed then a bunch of fallbacks will also be busted.

**Comment by bakkot** [comment]
Ehh, I don't think that's any more likely to be an issue than, e.g., `defaultSrc 'self'`. It's hard to know how bad the consequences of any given mistake will be.

**Comment by kingthorin** [comment]
Fair enough.

**Pull request merged**
